### ISSUE TITLE
`service reconcile` idles at 100% CPU usage

### ISSUE THREAD

**Issue by matthewhughes-uw** [OpsLevel/kubectl-opslevel#167]
`kubectl opslevel service reconcile` appears to use 100% of a single process when idling. 

## Reproduction

The simplest way to reproduce is to just run the reconciler with no work to be done, i.e. create a config that will just exclude everything

``` yaml
# config.yaml
version: "1.2.0"
service:
  import:
    - selector:
        apiVersion: apps/v1
        kind: deployment
        excludes:
          # any filter that would exclude every object in k8s
          - .metadata.namespace != "not-a-real-namespace"
```

(In our actual use case we saw the CPU usage would start low, but then jump up once all the items were processed)

run the reconciler using this config and observe the CPU usage of this process and note that it quickly jumps to 100%:

``` console
$ OPSLEVEL_API_TOKEN=<redacted> go run main.go service reconcile --config=config.yaml
```

## Diagnosis

Add some CPU profiling:

``` patch
diff --git a/src/main.go b/src/main.go
index 6344caa..8697530 100644
--- a/src/main.go
+++ b/src/main.go
@@ -2,6 +2,8 @@
 
 import (
 	"fmt"
+	"os"
+	"runtime/pprof"
 
 	"github.com/opslevel/kubectl-opslevel/cmd"
 )
@@ -12,5 +14,10 @@
 )
 
 func main() {
+	if err := pprof.StartCPUProfile(os.Stdout); err != nil {
+		fmt.Fprintf(os.Stderr, "Failed to start profiling: %v", err)
+		os.Exit(1)
+	}
+	defer pprof.StopCPUProfile()
 	cmd.Execute(fmt.Sprintf("%s-%0.12s", version, commit))
 }
```

Capture the profile letting the program run for a few seconds after being stuck
at 100% to get a clear picture then interrupting with `ctrl-C`:

``` console
$ OPSLEVEL_API_TOKEN=<redacted> go run main.go service reconcile --config=config.yaml > cpu.prof
```

Inspecting the profile:

``` console
$ go tool pprof cpu.prof 
File: main
Type: cpu
Time: Jun 17, 2023 at 11:14am (BST)
Duration: 24.02s, Total samples = 21.42s (89.16%)
Entering interactive mode (type "help" for commands, "o" for options)
(pprof) top5 -cum
Showing nodes accounting for 0.01s, 0.047% of 21.42s total
Dropped 93 nodes (cum <= 0.11s)
Showing top 5 nodes out of 12
      flat  flat%   sum%        cum   cum%
     0.01s 0.047% 0.047%     21.33s 99.58%  github.com/opslevel/kubectl-opslevel/k8sutils.(*KubernetesController).mainloop
         0     0% 0.047%     21.33s 99.58%  k8s.io/apimachinery/pkg/util/wait.BackoffUntil
         0     0% 0.047%     21.33s 99.58%  k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1
         0     0% 0.047%     21.33s 99.58%  k8s.io/apimachinery/pkg/util/wait.JitterUntil
         0     0% 0.047%     21.33s 99.58%  k8s.io/apimachinery/pkg/util/wait.Until
```

It's clear we're stuck in
`github.com/opslevel/kubectl-opslevel/k8sutils.(*KubernetesController).mainloop`.
This is because with an empty queue `(*KubernetesController).getLength`
returns `0` so we never enter the `for` loop in
`(*KubernetesController)processNextItem` but always return `true` from the
function hence `mainloop` just infinitely looping.

This also means as soon as any item is added to the queue it will be processed

## Fix

The quickest hack I found to fix this was to just ensure `getLength` always returns a non-zero value:

``` patch
diff --git a/src/k8sutils/controller.go b/src/k8sutils/controller.go
index 128d942..f38b433 100644
--- a/src/k8sutils/controller.go
+++ b/src/k8sutils/controller.go
@@ -65,7 +65,7 @@ func setupSignalHandler() <-chan struct{} {
 
 func (c *KubernetesController) getLength() int {
 	current := c.queue.Len()
-	if current < c.maxBatch {
+	if current < c.maxBatch && current > 0 {
 		return current
 	} else {
 		return c.maxBatch
```

With this we will always enter the `for` loop in `processNextItem` and just
block on `c.queue.Get`

**Comment by cmanfre4** [comment]
I'd like to see a fix for this. It makes it hard to trust the telemetry coming from it. How much of a cpu allocation does it actually need?

**Comment by rocktavious** [comment]
@matthewhughes-uw and @cmanfre4 - We have unfortunately been putting this tool on the back burner for the past 6-9 months.  I come bearing news that this tool is now going to get some love for the next 3-6 weeks.  I have a whole host of changes i'll be implementing (along with a pretty large refactor that will ensure the codebase can be tested)

Thanks for doing this investigation - i will make sure a fix for this gets placed in the post refactor.

**Comment by rocktavious** [comment]
@matthewhughes-uw - we've refactored this portion out to a separate repo (so we can use its logic elsewhere in other projects) but in this refactor i dug into the client-go a bit and found that workqueue.Get() is intended to be a blocking operation for goroutines to not waste CPU.  You can see here https://github.com/OpsLevel/opslevel-k8s-controller/blob/main/controller.go#L91 that i've rejiggered the code a bit but the goroutine now properly waits for k8s informer to properly put something on to the queue to work so we should no longer see this in the next release of this tool.

I'm preparing the release today 🎉
