### ISSUE TITLE
erroneously including invalid aliases when the jq expression returns "null" but there is valid string data from the expression

### ISSUE THREAD

**Issue by rocktavious** [OpsLevel/kubectl-opslevel#36]
```
"Aliases": [
            "k8s:yellow-app1b-contact-extractor-deployment-yellow-app1b-ml-consumers",
            "k8s:null"
        ],
```

this should probably not happen and we should just drop the value but its not a simple fix because it was a valid parse of the JQ expression and returned a non-null string value because of the nature of it being a JQ string expression filter.

```
> echo '{}' | jq '"k8s:\(.metadata.name)"'
"k8s:null"    <- valid non-null string value which we propagate because its valid string data
> echo '{}' | jq '.metadata.name'  
null          <- json null value which we detect as null
```

**Comment by rocktavious** [comment]
I think the only fix we can suggest here is to use JQ logic to check if the lookup was null and then emit the string or null

```
> echo '{}' | jq '"k8s:\(.metadata.name)"'
"k8s:null" 

VS

> echo '{}' | jq '.metadata.name if . then "k8s:\(.)" else empty end'
null
> echo '{"metadata":{"name":"hello"}}' | jq '.metadata.name | if . then "k8s:\(.)" else empty end'
"k8s:hello"
```

**Comment by taimoorgit** [comment]
Closing because:

1. This has a `wontfix` tag and the issue is inactive
2. We fixed a very similar issue with null and jq expressions in the latest release: https://github.com/OpsLevel/opslevel-jq-parser/releases/tag/v2024.3.15
